title: "Oinam’s Blog"
description: "Taking care of kids and women. Save the planet, curb climate change. Progress exponentially."

baseurl: ""
url: "https://blog.oinam.com"

permalink: pretty
permalink: /:title/

markdown: kramdown
highlighter: rouge

username:
  twitter:  oinam
  github:   oinam

feed:
  posts_limit: 9
  author: Oinam

sass:
  style: compressed
  sourcemap: never

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings

optional_front_matter:
  remove_originals: true

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

defaults:
  - scope:
      path: '_posts'
      type: 'posts'
    values:
      layout: 'post'
      permalink: '/:year/:title/'

exclude:
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - README.*